version: "3"

services:
    nginx:
        build: .
        image: nginx_magic:latest
        container_name: nginx
        ports:
            - "80:8080"
        depends_on:
            - web
        volumes:
            - static_files:/srv
    web:
        build: .
        image: magic:latest
        container_name: webapp
        ports:
            - "8000"
        volumes:
            - static_files:/var/www
        depends_on:
          - db
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=sebastian23
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
networks:
    default:
volumes:
    static_files:
    pgdata: