version: "3"

services:
    nginx:
        image: nginx_magic:latest
        container_name: nginx
        ports:
            - "80:8080"
        depends_on:
            - web
        volumes:
            - static_files:/srv
    web:
        image: magic:latest
        container_name: webapp
        expose:
            - "8000"
        volumes:
            - static_files:/var/www
    db:
        image: postgres:12.3
        container_name: postgres
        env_file:
            - postgres.env
        expose:
            - "5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
networks:
    default:
volumes:
    static_files:
    pgdata: