version: "3.5"

services:
    nginx:
        build: .
        image: nginx_magic:latest
        container_name: nginx
        ports:
            - "80:8080"
        volumes:
            - static_files:/srv
        depends_on:
            - web
        networks:
            - db_backend
    web:
        build: .
        image: magic:latest
        container_name: webapp
        env_file:
            - django.env
        ports:
            - "8000"
        volumes:
            - static_files:/var/www
        networks:
            - db_backend

networks:
    db_backend:
        external: true
volumes:
    static_files: