version: "3.5"

services:
    db:
        image: postgres:12.3
        container_name: db
        env_file:
            - postgres.env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend

networks:
    backend:
volumes:
    pgdata: